### ISSUE TITLE
osm-analytic-tracker unable to receive updates after router losing connection

### ISSUE THREAD

**Issue by Davide-sd** [MichaelVL/osm-analytic-tracker#13]
Hello,
I'm testing this tool on a Raspberry Pi 2 model B, with Raspbian Jessie. [These are the steps](https://wiki.openstreetmap.org/wiki/User:Davide_sd/OSM_Analytic_Tracker) I followed to get the tool up and running. 

The problem arise when the router (to which the Raspberry Pi is connected) loses the connection. When the router comes back online, the service is unable to re-establish the connection: "lag" field increase indefinitely, obviously without getting any updates.

When that happens, I have to completely stop and remove the container, and then running it again.

I'm looking into the code to find the problem, but I probably need help with this.

**Comment by michaelvl** [comment]
Hi,

I have myself used a similar approach on a raspberry for quite a long time. 
Its only recently I switched to a full x86 Kubernetes based setup...

What you could do is to look into the following file inside the container:

/osmtracker/osmtracker.log

As you can see from 'docker/supervisord.conf' file, the various sub-components 
have their own log file.

In the supervisord.conf file you can also add a '-lDEBUG' flag to make the 
different components output more logs.

Note that if the lag increase it can also be the backend that has problems - 
look into the '/osmtracker/backends.log' file for output from this.

One problem I have encountered on the raspberry is that mongodb refuse to sort 
changesets due to resource limitations. I'm not sure if this is due to the 
raspberry builds of mongodb or a missing index declaration in the code. I have 
not experienced a similar problem on x86 systems.

I hope this helps you.

PS: Your write-up on using osm analytic tracker on a raspberry looks really 
good - I might reference it from the github repo if you don't mind?

Regards,
Michael

**Comment by Davide-sd** [comment]
Hello Michael,
apparently today I'm not able to replicate the problem. I've rebooted the router several times, and also the raspberry. Seems like this problem was some kind of bad lack... Thank you for pointing out the logs! I've checked them and everything seems normal. I'm closing the issue!

> PS: Your write-up on using osm analytic tracker on a raspberry looks really good - I might reference it from the github repo if you don't mind?

No problem at all, happy to help as many people as possible :)
