### ISSUE TITLE
missing diffmap.php

### ISSUE THREAD

**Issue by yogiks** [MichaelVL/osm-analytic-tracker#6]
VisuallDiff needs links to diffmap.php at the [danish](http://osm.expandable.dk/osm/index.html) instance. But this seems to be missing inside html/ directory in the repo.

**Comment by poempelfox** [comment]
I've just been trying out this interesting project and noticed that too.
Also, some images (node.png, way.png, relation.png, note.png) seem to be missing too.

**Comment by poempelfox** [comment]
Since that PHPs only job seems to be to insert the changeset-id in one place and coordinates in two places into an otherwise static HTML page, I quickly hacked myself a replacement in perl from the HTML source of the demo instance: https://gist.github.com/poempelfox/b4d18e719eccee27c10a
Maybe useful for others until the proper script surfaces...

**Comment by yogiks** [comment]
> https://gist.github.com/poempelfox/b4d18e719eccee27c10a

Worked great! Thank you :+1:

**Comment by michaelvl** [comment]
Hi,
Thanks for noticing this - I have pushed some missing files - let me know if this fixes your issues.

/M
